### PR TITLE
Partially fix #70

### LINKED ISSUE #70: 7.5" V2 display driver does not work
A few things I found while trying to get my display to work as expected:
* `epd7in5_v2v::EPD7in5::new(...)` hangs [here](https://github.com/caemor/epd-waveshare/blob/main/src/epd7in5_v2/mod.rs#L72) since the `wait_until_idle` implementation is wrong. In the [example C code provided by Waveshare](https://github.com/waveshare/e-Paper/blob/7c368a22afb5456fb4622c617e792bd2f83e878b/RaspberryPi_JetsonNano/c/lib/e-Paper/EPD_7in5_V2.c#L78) one can see that the driver sends a `GET_STATUS` command and waits 20ms.  This seems to be needed otherwise the busy pin wont update which is the root cause to the problem.

* Black and White seems to have been mixed up. Setting the fill-color to black makes the display white and vice versa. Same thing goes for text colors/background.

**A few things that might be important:**
* Cross-compiling from Arch Linux x64_64 to aarch64 with `aarch64-linux-gnu-gcc` targeting `aarch64-unknown-linux-musl`.
* Using the [rppal](https://github.com/golemparts/rppal) crate with the hal-unproven feature.
* Running on Raspberry Pi OS 64-bit Beta (Kernel 5.4.51-v8+) on a Raspberry Pi 3b+.

A hacked together version of epd-waveshare can be found [here](https://github.com/olback/epd-waveshare/tree/7.5hack) and an example can be found [here](https://github.com/olback/smart-home/blob/epd-working/portal/src/main.rs).

### PR DESCRIPTION
**Pull request by olback**
This is unfortunately a breaking change but it makes it easier to add more displays with similar requirements to the 7.5" V2 display.

### CODE REVIEW

File: src/traits.rs [hunk 1]
```diff
@@ -275,13 +280,14 @@ where
...
 ///```
-pub trait QuickRefresh<SPI, CS, BUSY, DC, RST>
+pub trait QuickRefresh<SPI, CS, BUSY, DC, RST, DELAY>
 where
     SPI: Write<u8>,
     CS: OutputPin,
     BUSY: InputPin,
     DC: OutputPin,
     RST: OutputPin,
+    DELAY: DelayMs<u8>,
```
Comment (caemor) [inline src/traits.rs:290]: Is the delay necessary for any of the QuickRefresh functions? And if it is we need to add the delay to these.

File: src/interface.rs [hunk 2]
```diff
@@ -126,15 +130,32 @@ where
...
-            //old: shorten the time? it was 100 in the beginning
-            //self.delay_ms(5);
+            match task {
+                // TODO: Ignore this error?
+                Some((ref mut spi, ref mut delay, tcb)) => tcb(self, spi, delay)?,
+                None => {}
+            }
+            // //tested: REMOVAL of DELAY: it's only waiting for the signal anyway and should continue work asap
+            // //old: shorten the time? it was 100 in the beginning
+            // //self.delay_ms(5);
```
Comment (caemor) [inline src/interface.rs:156]: Since we need to insert a function here anyway wouldn't it be better to just "overwrite" the waveshare.wait_until_idle and handle everything there already (at a higher level) for these specific cases?

File: src/epd7in5_v2/mod.rs [hunk 3]
```diff
@@ -223,8 +228,16 @@ where
...
+    fn wait_until_idle(&mut self, spi: &mut SPI, delay: &mut DELAY) -> Result<(), SPI::Error> {
+        self.interface.wait_until_idle(
+            IS_BUSY_LOW,
+            Some((spi, delay, |i, s, d| {
+                i.cmd(s, Command::GET_STATUS)?;
+                d.delay_ms(20);
+                Ok(())
+            })),
+        )?;
+        Ok(())
```
Comment (caemor) [inline src/epd7in5_v2/mod.rs:240]: See the command in the interface. But wouldn't it be easier to just handle everything here already?

**Review by caemor — CHANGES_REQUESTED** [review]
Thanks for the PR. 
The PR looks good. I'm a bit conflicted about the changes to the `Interface`- and `QuickRefresh`-Trait and would be happy to your feedback to my comments in these parts.

File: src/interface.rs (hunk 2 above)
Comment (caemor) [reply src/interface.rs:156]: If not we should add a small doc example to highlight how it can be used (or link to the 7in5 v2 impl of yours above)

File: src/epd7in5_v2/mod.rs (hunk 3 above)
Comment (olback) [reply src/epd7in5_v2/mod.rs:240]: No idea why I made it this complicated.
Should be as easy as
```
while self.interface.is_busy(IS_BUSY_LOW) {
    self.interface.cmd(Command::GET_STATUS)?;
    delay.delay_ms(20);
}
Ok(())
```

**Review by caemor — APPROVED** [review]

**Comment by caemor** [comment]
It would be great if you could reapply your changes/merge the main so the conflicts are resolved else I can do it on the weekend .

Thanks for your work!
